### ISSUE TITLE
Allow evaluation of ClientFunction and Selectors in the browser console

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-live#14]

**Comment by jianentrinsik** [comment]
Thanks Andrey! Your team is doing awesome work, and testcafe is getting more fun to play with every release.

**Comment by AndreyBelym** [comment]
I close this issue because it became a duplicate of issue https://github.com/DevExpress/testcafe/issues/3244 after merging TestCafe Live into the TestCafe core.
