### ISSUE TITLE
Error when using testcafe-angular-selectors

### ISSUE THREAD

**Issue by Nierrrrrrr** [DevExpress/testcafe-live#16]
Hi, all.

My test case failed at `waitForAngular()` call when I use testcafe-live, and it's okay if I use testcafe.

My test case is very simple:

```
import {waitForAngular} from "testcafe-angular-selectors";

fixture `Getting Started`
  .page `http://www.google.com/`
  .beforeEach(async () => {
    await waitForAngular();
  });

test ('My first test', async t => {
  await t;
});
```

When I run it with testcafe-live, the error occurs:
```
1) - Error in fixture.beforeEach hook -
  Error: Cannot prepare tests due to an error.

  ClientFunction cannot implicitly resolve the test run in context of which it should be executed. If you need to call ClientFunction from the Node.js API callback, pass the test controller manually via ClientFunction's `.with({ boundTestRun: t })` method first. Note that you cannot execute ClientFunction outside the test code.
```

**Comment by AlexanderMoskovkin** [comment]
To fix the issue we should do like here: https://github.com/DevExpress/testcafe/blob/master/src/cli/index.js#L17

**Comment by nathanBrenner** [comment]
Another way to resolve this:

where `await waitForAngular();`, replace with

```
await ClientFunction(() => waitForAngular()).with({ boundTestRun: t });
```

**Comment by AndreyBelym** [comment]
I can't reproduce the issue with Live mode integrated into `testcafe@1.0.0`: [TestCafe 1.0.0 Released: Live mode](https://devexpress.github.io/testcafe/blog/testcafe-v1-0-0-released.html#live-mode-3215). If you still can reproduce with `testcafe@1.0.0`, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) in the main TestCafe repository.
