### ISSUE TITLE
Watching stops after first change

### ISSUE THREAD

**Issue by phortx** [DevExpress/testcafe-live#23]
I have a strange behavior here. I run `testcafe-live --page-load-timeout 60 -Ss 'tmp/testcafe/screenshots' -a 'bin/webpack' chrome e2e/`

This works very well. The tests run through. After that I change my test file and the tests automatically run again. But when I change the file again, nothing happens until I restart testcafe-live.

Do you have any idea how this could happen?

I'm thankful for any advice :)

**Comment by eddiegroves** [comment]
I have the same problem - the live reload works once then it appears to hang. `ctrl+r` doesn't work correctly either. Using Windows 10. 

Guess this project is still experiment/not a priority at the moment. Seems like a cool idea though!

**Comment by sydro** [comment]
same problem with testcafe@0.23.0 and testcafe-live@0.1.3 on linux

**Comment by sydro** [comment]
with downgrade of async-exit-hook (dep of testcafe-live) to version 1.1.2 it works fine again! Maybe async-exit-hook 2.0.1 is the problem.

**Comment by joma74** [comment]
Downgrading to `1.1.2` does not work for me.

**Comment by AndreyBelym** [comment]
I can't reproduce the issue with Live mode integrated into `testcafe@1.0.0`: [TestCafe 1.0.0 Released: Live mode](https://devexpress.github.io/testcafe/blog/testcafe-v1-0-0-released.html#live-mode-3215). If you still can reproduce with `testcafe@1.0.0`, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) in the main TestCafe repository.
