### ISSUE TITLE
Possible to run testcafe-live via Node?

### ISSUE THREAD

**Issue by amirse80** [DevExpress/testcafe-live#26]
Hi,
Is it possible to run testcafe-live version via node?
I would like to start my runner class from CMD ">node tRunner.js chrome" but I would actually like to start the live version. I.e. I would like to monitor the test via devtools.

What should I write in my tRunner.js file in order to starta the testcafe-live version?
return runner
            .src('./tTest.js')
            .browsers([args])

**Comment by AndreyBelym** [comment]
TestCafe Live doesn't have a proper API yet, but you can use the [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) to start it in another process.
