### ISSUE TITLE
Testcafe-live does not reflect changes

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-live#5]
cloned from https://github.com/DevExpress/testcafe/issues/2115 (created by @hdorgeval)

### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
When changing code outside the test file, testcafe-live restarts the test but saved modifications seems to be ignored.

### What is the expected behavior?
testcafe-live should reflect the most recent save

### How would you reproduce the current behavior (if this is a bug)?
Clone the github repo testcafe-starter
rename the file "testcafe-sample-page.spec.ts" to "testcafe-sample-page.live.ts"
Set .only to the test "Scenario: can send feedback with my name only"
run the command npm run test:live 
Open the file "i-enter-my-name.ts"
Comment the line ".typeText(...."
Save the file

=> testcafe-live restart the test, but text is still typed in the field

#### Provide the test code and the tested page URL (if applicable)
https://github.com/hdorgeval/testcafe-starter

Tested page URL:

Test code

```js

```

### Specify your

* operating system: windows 10 & MacOSX
* testcafe version: 0.18.6
* node.js version: 9.2.0

**Comment by AlexanderMoskovkin** [comment]
fixed in `0.1.2`

**Comment by hdorgeval** [comment]
Thanks @AlexanderMoskovkin for your reactivity. Testcafe-live is a fantastic add-on. I have worked with it since several days and now cannot work on testcafe without it. Thanks for delivering such high quality product. I encourage everybody to use it with Testcafe 👍
